package com.liteon.icgwearable.hibernate.entity;

// Generated Mar 1, 2017 12:29:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Announcement generated by hbm2java
 */
@Entity
@Table(name = "announcement")
public class Announcement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8138291151918313597L;
	@Id
	@GeneratedValue
	@Column(name = "announcement_id", unique = true, nullable = false)
	private Integer announcementId;
	@Column(name="school_id")
	private int schoolId;
	@Column(name = "name")
	private String name;
	@Column(name = "description")
	private String description;
	
	@Value("${display.dateTime}")
	@Column(name = "created_date", columnDefinition="DATETIME")
	@DateTimeFormat(pattern="${display.dateTime}")
	private Date createdDate;
	@Column(name = "updated_date", columnDefinition="DATETIME")
	@DateTimeFormat(pattern="${display.dateTime}")
	private Date updatedDate;

	public Announcement() {
	}

	public Integer getAnnouncementId() {
		return this.announcementId;
	}

	public void setAnnouncementId(Integer announcementId) {
		this.announcementId = announcementId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	public int getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}
}
