package com.liteon.icgwearable.hibernate.entity;

// Generated Mar 1, 2017 12:29:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * DeviceEventsQueue generated by hbm2java
 */
@Entity
@Table(name = "device_events_queue")
public class DeviceEventsQueue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8869992142682991501L;
	@Id
	@GeneratedValue
	@Column(name = "queue_id", unique = true, nullable = false)
	private Integer queueId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_event_id", nullable = false)
	private DeviceEvents deviceEvents;
	@Column(name = "queue_sent")
	private Integer queueSent;
	@Column(name = "queue_sent_date", columnDefinition="DATETIME")
	@DateTimeFormat(pattern="dd-MM-yyyy  HH:mm:ss")
	private Date queueSentDate;
	@Column(name = "created_date", columnDefinition="DATETIME")
	@DateTimeFormat(pattern="dd-MM-yyyy  HH:mm:ss")
	private Date createdDate;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private Users users;
	
	@Column(name = "android_app_token")
	private String androidAppToken;
	public String getandroidAppToken() {
		return androidAppToken;
	}

	public void setandroidAppToken(String androidAppToken) {
		this.androidAppToken = androidAppToken;
	}

	public String getiPhoneAppToken() {
		return iPhoneAppToken;
	}

	public void setiPhoneAppToken(String iPhoneAppToken) {
		this.iPhoneAppToken = iPhoneAppToken;
	}

	@Column(name = "iphone_app_token")
	private String iPhoneAppToken;
	@Column(name = "isEliminated" , columnDefinition="enum('y','n')")
	private String isEliminated;

	public DeviceEventsQueue() {
	}

	public DeviceEventsQueue(EventSubscriptions eventSubscriptions,
			DeviceEvents deviceEvents) {
		this.deviceEvents = deviceEvents;
	}

	public DeviceEventsQueue(EventSubscriptions eventSubscriptions,
			DeviceEvents deviceEvents, Integer queueSent, Date queueSentDate) {
		this.deviceEvents = deviceEvents;
		this.queueSent = queueSent;
		this.queueSentDate = queueSentDate;
	}
	
	public DeviceEventsQueue(EventSubscriptions eventSubscriptions,
			DeviceEvents deviceEvents, Integer queueSent, Date queueSentDate, String isEliminated) {
		this.deviceEvents = deviceEvents;
		this.queueSent = queueSent;
		this.queueSentDate = queueSentDate;
		this.isEliminated = isEliminated;
	}

	public Integer getQueueId() {
		return this.queueId;
	}

	public void setQueueId(Integer queueId) {
		this.queueId = queueId;
	}

	public DeviceEvents getDeviceEvents() {
		return this.deviceEvents;
	}

	public void setDeviceEvents(DeviceEvents deviceEvents) {
		this.deviceEvents = deviceEvents;
	}

	public Integer getQueueSent() {
		return queueSent;
	}

	public void setQueueSent(Integer queueSent) {
		this.queueSent = queueSent;
	}

	public Date getQueueSentDate() {
		return this.queueSentDate;
	}

	public void setQueueSentDate(Date queueSentDate) {
		this.queueSentDate = queueSentDate;
	}
	
	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getIsEliminated() {
		return isEliminated;
	}

	public void setIsEliminated(String isEliminated) {
		this.isEliminated = isEliminated;
	}
}
