package com.liteon.icgwearable.hibernate.entity;

// Generated Mar 1, 2017 11:14:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rewards generated by hbm2java
 */
@Entity
@Table(name ="rewards")
public class Rewards implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3794040423819087595L;
	@Id
	@GeneratedValue
	@Column(name = "reward_id", unique = true, nullable = false)
	private Integer rewardId;
/*	@ManyToOne
	@JoinColumn(name = "school_id", nullable = false)
	private Accounts accounts;*/
	/*@ManyToOne
	@JoinColumn(name = "teacher_id", nullable = false)
	private Users users;*/
	/*@ManyToOne
	@JoinColumn(name = "student_id")
	private Students students;*/
	
	@ManyToOne
	@JoinColumn(name = "rewards_category_id")
	private RewardsCategory rewardsCategory;
	
	@Column(name = "name")
	private String name;
	
	@Column(name = "reward_icon_url")
	private String reward_icon_url;
	
	//@Column(name = "description")
	//private String description;
	
	public RewardsCategory getRewardsCategory() {
		return rewardsCategory;
	}

	public void setRewardsCategory(RewardsCategory rewardsCategory) {
		this.rewardsCategory = rewardsCategory;
	}

	@Column(name = "created_date", columnDefinition="DATETIME")
	private Date createdDate;
	@Column(name = "updated_date", columnDefinition="DATETIME")
	private Date updatedDate;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rewards")
	private Set<RewardsStudents> rewardsStudents = new HashSet<RewardsStudents>(0);

	public Set<RewardsStudents> getRewardsStudents() {
		return rewardsStudents;
	}

	public void setRewardsStudents(Set<RewardsStudents> rewardsStudents) {
		this.rewardsStudents = rewardsStudents;
	}

	public Rewards() {}

	public Integer getRewardId() {
		return this.rewardId;
	}

	public void setRewardId(Integer rewardId) {
		this.rewardId = rewardId;
	}

/*	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}*/

	/*public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}*/

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}*/

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getReward_icon_url() {
		return reward_icon_url;
	}

	public void setReward_icon_url(String reward_icon_url) {
		this.reward_icon_url = reward_icon_url;
	}

	/*public Set getRewardsStudentses() {
		return this.rewardsStudentses;
	}

	public void setRewardsStudentses(Set rewardsStudentses) {
		this.rewardsStudentses = rewardsStudentses;
	}*/
	
	
	/*public Students getStudents() {
		return students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}*/
	

}
