package com.liteon.icgwearable.hibernate.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "students")
public class Students implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8797043238649519803L;
	@Id
	@GeneratedValue
	@Column(name = "student_id", unique = true, nullable = false)
	private Integer studentId;
	@Column(name = "name")
	private String name;
	@Column(name = "nickname")
	private String nickName;
	@Column(name = "emergency_contact")
	private String emergencyContactNo;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_grade_id", nullable = false)
	private ClassGrade classGrade;
	@Column(name = "roll_no")
	private String rollNo;
	@Column(name = "dob" , columnDefinition = "DATETIME")
	private Date dob;
	@Column(name = "height")
	private Float height;
	@Column(name = "weight")
	private Float weight;
	@Column(name = "gender",columnDefinition="enum('MALE','FEMALE')")
	private String gender;
	@Column(name="registartion_no")
	private String registartion_no;
	@Column(name="allergies")
	private String allergies;
	@Column(name = "created_date", columnDefinition="DATETIME")
	private Date createDate;
	@Column(name = "updated_date", columnDefinition="DATETIME")
	private Date updatedDate;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	private Set<RewardsStudents> rewardsStudentses = new HashSet<RewardsStudents>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	@JsonIgnore
	private Set<ParentKids> parent_kids = new HashSet<ParentKids>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	@JsonIgnore
	private Set<DeviceStudents> deviceStdents = new HashSet<DeviceStudents>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	private Set<EventSubscriptions> eventSubscriptions = new HashSet<EventSubscriptions>(0);
	
		public Set<EventSubscriptions> getEventSubscriptions() {
		return eventSubscriptions;
	}

	public void setEventSubscriptions(Set<EventSubscriptions> eventSubscriptions) {
		this.eventSubscriptions = eventSubscriptions;
	}

	public Students() {}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getStudentId() {
		return studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<RewardsStudents> getRewardsStudentses() {
		return rewardsStudentses;
	}

	public void setRewardsStudentses(Set<RewardsStudents> rewardsStudentses) {
		this.rewardsStudentses = rewardsStudentses;
	}


	public void setName(String name) {
		this.name = name;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	
	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}
	
	public String getEmergencyContactNo() {
		return emergencyContactNo;
	}

	public void setEmergencyContactNo(String emergencyContactNo) {
		this.emergencyContactNo = emergencyContactNo;
	}

	public Float getHeight() {
		return height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getWeight() {
		return weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public String getAllergies() {
		return allergies;
	}

	public void setAllergies(String allergies) {
		this.allergies = allergies;
	}

	public String getName() {
		return name;
	}
	
	public ClassGrade getClassGrade() {
		return classGrade;
	}

	public void setClassGrade(ClassGrade classGrade) {
		this.classGrade = classGrade;
	}
	public Set<DeviceStudents> getDeviceStdents() {
		return deviceStdents;
	}

	public void setDeviceStdents(Set<DeviceStudents> deviceStdents) {
		this.deviceStdents = deviceStdents;
	}
	
	public Set<ParentKids> getParentKids() {
		return parent_kids;
	}

	public void setParentKids(Set<ParentKids> parentKids) {
		this.parent_kids = parentKids;
	}

	public String getRollNo() {
		return rollNo;
	}

	public void setRollNo(String rollNo) {
		this.rollNo = rollNo;
	}

	public String getRegistartion_no() {
		return registartion_no;
	}

	public void setRegistartion_no(String registartion_no) {
		this.registartion_no = registartion_no;
	}
}
