source("src/cassandraFuncs.R")

school.id <- getKeyspaces()
#RenameKeySpacesTableColumn(school.id, "context_hour", "datehour", "ts")
#RenameKeySpacesTableColumn(school.id, "context_date", "date", "ts")
#RenameKeySpacesTableColumn(school.id, "context_week", "wdate", "ts")
#RenameKeySpacesTableColumn(school.id, "context_month", "mdate", "ts")
#RenameKeySpacesTableColumn(school.id, "step_hour", "datehour", "ts")
#RenameKeySpacesTableColumn(school.id, "step_date", "date", "ts")
#RenameKeySpacesTableColumn(school.id, "step_week", "wdate", "ts")
#RenameKeySpacesTableColumn(school.id, "step_month", "mdate", "ts")
RenameKeySpacesTableColumn(school.id, "hrm_hour", "datehour", "ts")
RenameKeySpacesTableColumn(school.id, "hrm_date", "date", "ts")
RenameKeySpacesTableColumn(school.id, "hrm_week", "wdate", "ts")
RenameKeySpacesTableColumn(school.id, "hrm_month", "mdate", "ts")
#RenameKeySpacesTableColumn(school.id, "sleep_hour", "datehour", "ts")
#RenameKeySpacesTableColumn(school.id, "sleep_date", "date", "ts")
#RenameKeySpacesTableColumn(school.id, "sleep_week", "wdate", "ts")
#RenameKeySpacesTableColumn(school.id, "sleep_month", "mdate", "ts")
