######################################################################
# Automatically generated by qmake (3.0) Fri Mar 1 22:30:14 2013
######################################################################

TEMPLATE = app
TARGET = splitsentence-cpp-bolt
QT += testlib

# Input
HEADERS += \
    qtuple.h \
    qbasicbolt.h \
    splitsentence.h
SOURCES += main.cpp \
    qbasicbolt.cpp \
    splitsentence.cpp \
    testsplitsentence.cpp
